#spring.application.name=auth-service
server:
  base-url: localhost
  port: 9443
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    enabled: false
#    key-store: classpath:keystore.p12
#    key-store-password: 8llow8llowme
#    key-store-type: PKCS12
spring:
  application:
    name: auth-service
  devtools:
    restart:
      enabled: false
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/ # Eureka ?? ??
      instance:
        hostname: localhost
        prefer-ip-address: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB ????
    url: jdbc:mysql://${server.base-url}:3306/spring?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # ?????? URL
    username: root                    # ?????? ???
    password: 8llow8llowme                   # ?????? ?? ????

  # data_????.sql ?? ?? setting (?????)
  #  sql:
  #    init:
  #      mode: always
  #      data-locations:
  #        - 'classpath:/db/dummy/FOREIGN_KEY_CHECKS_0.sql'
  #        - 'classpath:/db/dummy/db_dump.sql'
  #        - 'classpath:/db/dummy/db_dump1.sql'
  #        - 'classpath:/db/dummy/db_dump2.sql'
  #        - 'classpath:/db/dummy/FOREIGN_KEY_CHECKS_1.sql'

  # NoSQL setting
  data:
    # Redis setting
    redis:
      host: ${server.base-url}
      port: 6379

  # JSP Setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

jwt:
  accessKey: "w7Dd0jmlEjFvWfnH8xCyAaD4J9KeShMQEfK5TZZjbgM="
  refreshKey: "YrLk76XDh9TaBtKxN+WxMr1Zm+zKlOPUv6RJqz9TZYI="
  accessExpiration: PT420M  # 420분 (PT420M)
  refreshExpiration: PT10080M  # 10080분 (7일) (PT10080M)

# log 관리
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug


oauth:
  kakao:
    client-id: e1be41bbfbb498c203c87ef3b5a7edc3 # REST API 키
    client-secret: a6QyXOAtiuidFN4mOt44ZrvuRciYGwCx # 보안 -> Client Secret 키
    redirect-uri: http://${server.base-url}:8443/auth/oauth/KAKAO/login
    scope:
      - profile_nickname
      - profile_image
      - account_email