server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 8llow8llowme
    key-store-type: PKCS12
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'https://localhost:9443'
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: auth-service
          uri: https://localhost:9443
          predicates:
            - Path=/auth/**
        - id: member-service
          uri: http://localhost:9001
          predicates:
            - Path=/member/**
          filters:
            - name: AuthValidationFilter
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
          filters:
            - name: AuthValidationFilter

    discovery:
      locator:
        enabled: true
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
