server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 8llow8llowme
    key-store-type: PKCS12

spring:
  application:
    name: gateway-service
  devtools:
    restart:
      enabled: false
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: https://localhost:9443/
          predicates:
            - Path=/auth/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: DEBUG

