server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 8llow8llowme
    key-store-type: PKCS12

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          filters:
            - RemoveRequestHeader=Cookie
          predicates:
            - Path=/auth/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
