#spring.application.name=community-service
server:
  base-url: localhost
  port: 9002
spring:
  application:
    name: community-service
  devtools:
    restart:
      enabled: false
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/ # Eureka ?? ??
      instance:
        hostname: localhost
        prefer-ip-address: true

  servlet:
    # file 업로드 관련 세팅 (명시적으로 설정 안할 시 Spring boot는 기본적으로 1MB로 설정됨)
    multipart:
      max-file-size: 10MB  # 최대 파일 크기
      max-request-size: 10MB  # 최대 요청 크기

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    generate-ddl: false
    hibernate:
      ddl-auto: update          # ddl 자동 작성 여부
    properties:
      hibernate:
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        use_sql_comments: true
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB ????
    url: jdbc:mysql://${server.base-url}:3307/spring?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # ?????? URL
    username: root                    # ?????? ???
    password: 8llow8llowme

  # NoSQL setting
  data:
    # Redis setting
    redis:
      host: ${server.base-url}
      port: 6379

  # JSP Setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# log 관리
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

jwt:
  accessKey: "w7Dd0jmlEjFvWfnH8xCyAaD4J9KeShMQEfK5TZZjbgM="
  refreshKey: "YrLk76XDh9TaBtKxN+WxMr1Zm+zKlOPUv6RJqz9TZYI="
  accessExpiration: PT420M  # 420분 (PT420M)
  refreshExpiration: PT10080M  # 10080분 (7일) (PT10080M)
