#spring.application.name=eureka
spring:
  application:
    name: eureka-server
  devtools:
    restart:
      enabled: false

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true
